name: test
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: download the src to runner env
              uses: actions/checkout@v4
            - name: install node js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: install node js dependencies
              run: npm install
            - name: run tests
              run : npm test
